export type CalendarEvent = { id: string; title: string; date: string; time: string; end: string; type: string; location: string; status: string; description: string; };
export type Design = { layout: 'programme' | 'calendar'; device: 'desktop' | 'phone'; palette: number; monthPalette: boolean; heading: number; fontSize: number; showTime: boolean; showLocation: boolean; showBrand: boolean; showMini: boolean; safeArea: boolean; language: 'en' | 'ar'; brand: string; customBg: string; customFg: string; };
export const MONTHS = ['January','February','March','April','May','June','July','August','September','October','November','December'];
export const TYPES = ['Workshop','Training','Ceremony','Internal meeting','Committee meeting','Event'];
export const TYPE_COLORS: Record<string,string> = {'Workshop':'#47785f','Training':'#4e7d9d','Ceremony':'#9c7341','Internal meeting':'#797469','Committee meeting':'#84618c','Event':'#a9654c'};
export const PALETTES = [{name:'Sand',bg:'#d9ceb7',fg:'#252820'},{name:'Forest',bg:'#314936',fg:'#f4f3e8'},{name:'Sage',bg:'#a5c5b5',fg:'#172c24'},{name:'Ocean',bg:'#16384a',fg:'#f0f4ed'},{name:'Sky',bg:'#dae5f2',fg:'#1b2a37'},{name:'Clay',bg:'#be7158',fg:'#211e1a'},{name:'Butter',bg:'#f2d450',fg:'#252519'},{name:'Walnut',bg:'#827059',fg:'#fff9ed'}];
export const MONTH_PALETTES = [4,3,2,1,1,6,5,5,0,7,1,4];
export const DEFAULT_DESIGN: Design = {layout:'programme',device:'desktop',palette:0,monthPalette:false,heading:100,fontSize:100,showTime:true,showLocation:true,showBrand:true,showMini:true,safeArea:false,language:'en',brand:'AGENDATI',customBg:'',customFg:'',};
export const dateKey=(year:number,month:number,day:number)=>`${year}-${String(month+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;
export const daysInMonth=(year:number,month:number)=>new Date(Date.UTC(year,month+1,0)).getUTCDate();
export const dayOffset=(year:number,month:number)=>(new Date(Date.UTC(year,month,1)).getUTCDay()+6)%7;
export const monthName=(year:number,month:number,language='en')=>new Intl.DateTimeFormat(language==='ar'?'ar-AE':'en-GB',{month:'long',timeZone:'UTC'}).format(new Date(Date.UTC(year,month,1)));
export function seedEvents():CalendarEvent[]{
 const result:CalendarEvent[]=[];
 for(let month=8;month<12;month++){
  const rows:[number,string,string,string][] = month===8?[[1,'Team alignment','Internal meeting','Meeting room 2'],[2,'Innovation roadmap','Committee meeting','Strategy room'],[9,'Ideas into action','Workshop','Innovation lab'],[15,'Team alignment','Internal meeting','Online · Teams'],[16,'Innovation review','Committee meeting','Strategy room'],[17,'Design thinking workshop','Workshop','Innovation lab'],[22,'Data storytelling','Training','Training room A'],[23,'Innovation roadmap','Committee meeting','Strategy room'],[29,'Quarterly team review','Internal meeting','Meeting room 2'],[30,'Innovation showcase','Event','Main auditorium']]:month===9?[[5,'Innovation sprint','Workshop','Innovation lab'],[6,'Team alignment','Internal meeting','Meeting room 2'],[7,'Committee review','Committee meeting','Strategy room'],[12,'Service design workshop','Workshop','Innovation lab'],[14,'Innovation committee','Committee meeting','Strategy room'],[15,'Innovation awards','Ceremony','Main auditorium'],[19,'Future thinking','Workshop','Innovation lab'],[20,'Team alignment','Internal meeting','Online · Teams'],[21,'Committee review','Committee meeting','Strategy room'],[26,'Ideas into action','Workshop','Innovation lab'],[27,'Team alignment','Internal meeting','Meeting room 2'],[28,'Innovation review','Committee meeting','Strategy room']]:[[3,'Team alignment','Internal meeting','Meeting room 2'],[9,'Ideas into action','Workshop','Innovation lab'],[17,'Innovation committee','Committee meeting','Strategy room'],[24,'Monthly showcase','Event','Main auditorium']];
  rows.forEach(([day,title,type,location],i)=>result.push({id:`demo-${month}-${i}`,title,date:dateKey(2026,month,day),time:i%3===0?'09:00':'10:00',end:i%3===0?'10:00':'11:30',type,location,status:'Published',description:'Demonstration event inspired by the 2026 calendar. Edit this entry to make it your own.'}));
 }
 return result;
}
export function eventsForMonth(events:CalendarEvent[],year:number,month:number,types:string[],status:string){return events.filter(e=>e.date.startsWith(`${year}-${String(month+1).padStart(2,'0')}`)&&types.includes(e.type)&&(status==='All statuses'||e.status===status)).sort((a,b)=>a.date.localeCompare(b.date)||a.time.localeCompare(b.time));}
